image: docker:20.10.16

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  REGISTRY: $CI_REGISTRY
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  CONTAINER_NAME: labtrac-frontend-main-build

stages:
  - build
  - deploy

build_and_push_container:
  stage: build
  only:
    - main
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:latest"
  artifacts:
    paths:
      - Dockerfile

deploy_to_ec2:
  stage: deploy
  only:
    - main
  image: alpine:latest
  dependencies:
    - build_and_push_container
  before_script:
    - apk update && apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST" << EOF
        sudo docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        sudo docker pull "$IMAGE_NAME:latest"

        if [ \$(sudo docker ps -q -f name=$CONTAINER_NAME) ]; then
          sudo docker stop $CONTAINER_NAME
          sudo docker rm $CONTAINER_NAME
        elif [ \$(sudo docker ps -a -q -f name=$CONTAINER_NAME) ]; then
          sudo docker rm $CONTAINER_NAME
        fi

        sudo docker run -d --name $CONTAINER_NAME -p 80:3000 "$IMAGE_NAME:latest"

        sudo docker system prune -f
EOF
